### ISSUE TITLE
Adding Port Setting

### ISSUE THREAD

**Issue by princeydev** [maurobonfietti/rest-api-slim-php#126]
Hi,
This is an awesome job, thank you so much. In my case the mysql server isn't running on the default port, I had to tweak the code a bit to allow for an additional setting.

in .env:
  DB_PORT='3308'

in extras/bin/restart-db.php:
    $dsn = "mysql:host=${hostname};port=${port};charset=utf8";
    $pdo = new PDO($dsn, $username, $password);

in src/app/dependencies.php:
    $port       = $db['port'];
    $dsn = sprintf('mysql:host=%s;dbname=%s;port=%s;charset=utf8', $db['hostname'], $db['database'], $db['port']);

Thanks again for this great project.

**Comment by maurobonfietti** [comment]
Hi @princeydev !
I'm glad you liked the project :grinning:
Thanks for your suggestion, I implemented in this PR  #127.
Best regards, Mauro.-
