### ISSUE TITLE
[ERROR] could not find driver - en composer restart-db

### ISSUE THREAD

**Issue by CraterMaik** [maurobonfietti/rest-api-slim-php#128]
Buenas, cuando pruebo el comando 
composer restart-db

Error: 
[ERROR] could not find driver

Tengo la base de datos creado en wamp server localhost:82/phpadmin

**Comment by maurobonfietti** [comment]
Buenas!

Consulta:

¿Tienes configurado en tu servidor local el driver de PDO para MySQL?

Haz un `phpinfo()` para fijarte si lo tienes habilitado.

Adicionalmente, ¿qué valor tienes configurado en tus variables de entorno?

Saludos!

**Comment by CraterMaik** [comment]
en phpinfo();
me sale esto:
PDO

PDO support => enabled
PDO drivers =>

en .env:

DB_HOST='localhost'
DB_NAME='api-rest'
DB_USER='root'
DB_PASS=''
DB_PORT='3306'

DISPLAY_ERROR_DETAILS=true
APP_DOMAIN='https://www.yourdomain.com'
SECRET_KEY='YourSuperSecret-KeY'

REDIS_ENABLED=false
REDIS_URL=''

**Comment by maurobonfietti** [comment]
Fijate si podes habilitar este modulo para PDO y MySQL: pdo_mysql

Yo tengo asi por ejemplo:

<img width="975" alt="Screen Shot 2020-12-10 at 14 00 33" src="https://user-images.githubusercontent.com/24535949/101804224-1ee7c580-3af0-11eb-9b31-76ba020391de.png">

**Comment by CraterMaik** [comment]
Revisando, no tengo la ext pdo_mysql
y para instalar, solo me sale este comando: 
sudo apt-get install php5-gd php5-mysql

Pero yo estoy utilizando window 10 y el CLI php como podria instalarlo desde hay? y debe ser .dll

**Comment by CraterMaik** [comment]
Listo, ya puedo ejecutar composer restart-db correctamente, gracias
