### ISSUE TITLE
Install warning

### ISSUE THREAD

**Issue by Solo-it** [maurobonfietti/rest-api-slim-php#151]
Hello

I see this:

Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.

![image](https://github.com/maurobonfietti/rest-api-slim-php/assets/79764140/c86df4d7-4278-4e66-88d7-40724f190d25)

**Comment by maurobonfietti** [comment]
It is fixed in version 2.22.0

https://github.com/maurobonfietti/rest-api-slim-php/releases/tag/v.2.22.0

Thank you @Solo-it !
