### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by ezetojo** [maurobonfietti/rest-api-slim-php#29]
https://rest-api-slim-php.herokuapp.com/api/v1/users/
works fine, ask for token

https://rest-api-slim-php.herokuapp.com/api/v1/users
is accesible

https://rest-api-slim-php.herokuapp.com/api/v1/users/#
works too without auth

**Comment by maurobonfietti** [comment]
**Hey Eze, thanks for the report!**

I just re-deploy the API in Heroku (from version 19.3 to 19.4).

It's a work in progress.

If you try again sending a request GET to: `/api/v1/users` the API ask for a token.

If you pass the header 'Authorization' with a valid JWT Token Bearer, the response will be the list of all users.

Example:
<img width="728" alt="Screenshot_92" src="https://user-images.githubusercontent.com/24535949/55924672-264f2100-5be1-11e9-91cd-b90a0240c68d.png">


If you try again sending a request GET to: `/api/v1/users/#` now, the API will ask for a token and the response will be something like:

```
{
    "message": "User not found.",
    "class": "UserException",
    "status": "error",
    "code": 404
}
```
<img width="731" alt="Screenshot_93" src="https://user-images.githubusercontent.com/24535949/55924734-70380700-5be1-11e9-9a91-35836fd8708e.png">

**Comment by ezetojo** [comment]
Nice @maurobonfietti! It's a great work. I don't understand enough php/slim to help coding but i'll try to use it in my project and report any issue to make it better! Thanks!
