### ISSUE TITLE
create user problem

### ISSUE THREAD

**Issue by xjunin** [maurobonfietti/rest-api-slim-php#36]
Hi
when try create user by api using you demo, this return { "message": "The field \"password\" is required.", "class": "UserException", "status": "error", "code": 400 } but in postman I send param for password.

https://rest-api-slim-php.herokuapp.com/api/v1/users?name=adson.junio&email=jungle@globo.com.br&password=Codec123

**Comment by maurobonfietti** [comment]
Hi @xjunin !

You can try sending the data inside the body of the POST request.

**For example:**

```
curl -X POST \
  https://rest-api-slim-php.herokuapp.com/api/v1/users \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: rest-api-slim-php.herokuapp.com' \
  -H 'Postman-Token: 39877e4c-628d-4da1-a62a-5069923559d6,18d9cd27-4848-40c1-bb01-a958a050bedd' \
  -H 'User-Agent: PostmanRuntime/7.11.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 83' \
  -d '{
  "name": "Name",
  "email": "your@email.com",
  "password": "YourPass123"
}'
```

I attached a screenshot.

<img width="726" alt="Screenshot_97" src="https://user-images.githubusercontent.com/24535949/56992454-7d0ca280-6b70-11e9-8d0a-5b59694995ba.png">

I'm working on the API documentation, it would be something like this:

https://github.com/maurobonfietti/rest-api-slim-php/blob/master/extras/docs/endpoints.md#4-create-user

I hope it helps!

**Comment by xjunin** [comment]
thanks for you help,
Sorry by my error.
