### ISSUE TITLE
Invalid HTTP status code 

### ISSUE THREAD

**Issue by jalpanmehta** [maurobonfietti/rest-api-slim-php#58]
I am getting following error eventhough passing JWT token to getalltask API.

Fatal error: Uncaught InvalidArgumentException: Invalid HTTP status code in F:\wamp64\www\testapi\vendor\slim\slim\Slim\Http\Response.php on line

**Comment by maurobonfietti** [comment]
Hi, @jalpanmehta.

Update this file: **src/Handler/ApiError.php** with this content:

```php
<?php declare(strict_types=1);

namespace App\Handler;

use Psr\Http\Message\ServerRequestInterface as Request;
use Psr\Http\Message\ResponseInterface as Response;

final class ApiError extends \Slim\Handlers\Error
{
    public function __invoke(Request $request, Response $response, \Exception $exception)
    {
        $statusCode = 500;
        if (is_int($exception->getCode()) && $exception->getCode() < 500) {
            $statusCode = $exception->getCode();
        }
        $className = new \ReflectionClass(get_class($exception));
        $data = [
            'message' => $exception->getMessage(),
            'class' => $className->getShortName(),
            'status' => 'error',
            'code' => $statusCode,
        ];
        $body = json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);

        return $response
                ->withStatus($statusCode)
                ->withHeader('Content-type', 'application/problem+json')
                ->write($body);
    }
}
```

**This new version must show a better error message.**

Try again and make a request to the endpoint: _**GET  /api/v1/tasks**_

Now check the response with the new error/exception message...

[I hope this help you to find the problem.]

**Comment by maurobonfietti** [comment]
Hello @jalpanmehta.

At this moment, I close this issue.

**If you have any problem or suggestion, just reopen this issue.**

Best regards.-
