### ISSUE TITLE
Gettin 500 error on every route with /[{id}]

### ISSUE THREAD

**Issue by f4t4l** [maurobonfietti/rest-api-slim-php#62]
Thanks for work, is is very easy to deploy with docker.
I am getting the following issue and as a beginner I need your help

`Fatal error: Uncaught InvalidArgumentException: ReasonPhrase must be supplied for this code in /var/www/html/vendor/slim/slim/Slim/Http/Response.php on line 204`

The strange thing is that there is a message key value for each.
It seems that it does this only for routes that contain [{id}] (GET, POST, PUT, DELETE).

I have just cloned and run the make up command.

Any idea?

**Comment by maurobonfietti** [comment]
Hi @f4t4l,

I'm working in a new version to fix this problem.

Please, try something like this:

1- Clone again the repo and run 'make up' and 'make vendor' (just in case):

```bash
git clone https://github.com/maurobonfietti/rest-api-slim-php.git && cd rest-api-slim-php
make up
make vendor
```

2- Then, create a `.env` config file:

```bash
$ cp .env.example .env
```

3- In the `.env` file, edit the environment variable: 'REDIS_URL' with this value:

```
REDIS_URL='tcp://redis:6379'
```

4- Finally, verify this endpoints:

```bash
curl http://localhost:8081
curl http://localhost:8081/status
curl http://localhost:8081/api/v1/notes
curl http://localhost:8081/api/v1/notes/3
```

Let me know if you can use with success the API with docker.

Thanks for your report.

**Comment by f4t4l** [comment]
Hi @maurobonfietti,

It works like a charm, thanks!
Far better to run and re run multiple times with docker.

Really appreciate your approach, now trying to mix it with another app based on Slim4.

**Comment by maurobonfietti** [comment]
Awesome.
All the best with your project in Slim 4!
Thanks again for your report.
