### ISSUE TITLE
"migration" tool.

### ISSUE THREAD

**Issue by Danack** [maurobonfietti/rest-api-slim-php#74]
Hi,

Someone just asked for help with using this project, and looking quickly I found that the ['database migration' script](https://github.com/maurobonfietti/rest-api-slim-php/blob/0ea5ffea9107ada9b48b37d2ee9cfd224a1a8f5e/extras/bin/migration.php) actually is more of a 'nuke from orbit and recreate from a backup' script.

This is just an opinion but:

If you're going to call it a DB migration tool, then it should probably behave like phinx or Doctrine migrations.

If it's intended to drop the existing database and restore from a backup, then it shouldn't be called a migration tool.

Having the capability for a 'migration' to destroy data is highly suprising.

cheers
Dan
Ack

**Comment by maurobonfietti** [comment]
Hi Dan, you are right.

It's not a migration tool.

I use this option to create/drop the database, just for development purpose only.

I just [release a new version](https://github.com/maurobonfietti/rest-api-slim-php/pull/75). I rename the file to: `restart-db.php`. Also, I change the command shortcut to: `composer restart-db`.

The real intention it's to have a command/script to initialize the database, when you start this API as a new project and this cmd should works in *nix and windows S.O.

Thank you so much your contribution!
