### ISSUE TITLE
Issue on the database > Dependencies.php file

### ISSUE THREAD

**Issue by fradducho** [maurobonfietti/rest-api-slim-php#96]
Hola, Buenas tardes.

Intentando probar tu api veo que me da un error al ejecutar el comando > "composer database" en la linea 18 del archivo  Dependencies.php.

He comentado la linea y ha funcionado a la primera podrias tomar nota  o decirme si ha sido causa algo mal condigurado?

Adjunto imagenes.

![error api](https://user-images.githubusercontent.com/21328059/84619963-aab3c880-aea4-11ea-9c47-075f2a23eea9.png)

Error al ejecutar "composer database"
![2020-06-15_01-05](https://user-images.githubusercontent.com/21328059/84619987-b8694e00-aea4-11ea-8c8e-f30becdb7601.png)

Funciona OK luego d e comentar la linea marcada en la primera imagen.
![app](https://user-images.githubusercontent.com/21328059/84619974-b0111300-aea4-11ea-8777-32370ac87537.png)

**Comment by maurobonfietti** [comment]
Buenas! Como estas @fradducho ?

Qué version de PHP estas utilizando?

Probá reescribir dicha línea de esta forma:

```php
$container['errorHandler'] = static function (): ApiError {
    return new ApiError();
};
```

**Comment by maurobonfietti** [comment]
Hello!

**I just released a new version 1.6.0**

This is the Pull Request with the new changes: https://github.com/maurobonfietti/rest-api-slim-php/pull/97

You can upgrade to this new version.

**The code now supports the latest versions of PHP. So you will need PHP 7.3 or 7.4**

If the error persist just let me know.

Thanks for reporting the issue.

**Comment by fradducho** [comment]
Hola Mauro,  He aplicado tus lineas de codigo y efectivamente ya funciona.

Mi version de PHP es: 7.3.19
![image](https://user-images.githubusercontent.com/21328059/85190323-4cf8f500-b285-11ea-92e4-75110d6b3ce5.png)


Te adjunto  imagenes.

![image](https://user-images.githubusercontent.com/21328059/85190338-69952d00-b285-11ea-86a0-66de411bf8c7.png)

**Comment by fradducho** [comment]
Hola Mauro, Mi version php es 7.3.19 y con esta ultima release 1.6.0 funciona 100%

Muchas Gracias.
